version: "3.1"
services:
  mysql:
    container_name: mysql57
    image: mysql:5.7
    volumes:
      - /home/vasya/Docker/storage/mysql57:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web
  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin
    links:
      - "mysql:db"
    ports:
      - "9988:80"
    restart: always
    networks:
      - web

networks:
  web:
    driver: bridge